### ISSUE TITLE
Actividad 2_Infografia

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-2-infografia-Jaczibeth#1]
Jaczibeth 1bs
![Infografía de Proceso de construccion del conocimiento](https://user-images.githubusercontent.com/112178026/188514811-edf0618b-eb9d-417b-a61e-246143c5cbb4.png)

**Comment by 11042002** [comment]
Tu calificación es de: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
